### ISSUE TITLE
Caught an exception while collecting.Java heap space

### ISSUE THREAD

**Issue by LiteWait** [BlueMedoraPublic/new-relic-plugins#17]
I am allocating 512MB of memory, but I am getting memory errors.

BTW I have 500 schemas.

```
com.bluemedora.exuno.common.ExUnoException: Caught an exception while collecting.Java heap space
	at com.bluemedora.exuno.DataProvider.collect(DataProvider.java:252)
	at com.bluemedora.newrelic.ExUnoAgent.collect(ExUnoAgent.java:226)
	at com.bluemedora.newrelic.ExUnoAgent.pollCycle(ExUnoAgent.java:115)
	at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:199)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at com.bluemedora.exuno.result.ExUnoCollectionResult.resourcesToString(ExUnoCollectionResult.java:807)
	at com.bluemedora.exuno.result.ExUnoCollectionResult.toString(ExUnoCollectionResult.java:789)
	at com.bluemedora.exuno.DataProvider.collect(DataProvider.java:243)
```

**Comment by afearbm** [comment]
Hi LiteWait,

My name is Andrew and I am part of the support team here at Blue Medora. With 500 schemas I would recommend increasing the memory allocation to 1024MB. This should take care of your memory errors. Have you tried that already? By the way, which plugin are you using?

Thanks,

Andrew
andrew.fear@bluemedora.com

**Comment by afearbm** [comment]
@LiteWait 

Were you able to resolve this issue?

Andrew
andrew.fear@bluemedora.com
